services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: .
            dockerfile: Dockerfile
        container_name: references
        volumes:
            - ./:/var/www
        depends_on:
            - db
        networks:
            - app-network
    db:
        image: postgres:15
        container_name: db_references
        restart: unless-stopped
        environment:
            POSTGRES_DB: references
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-network

    nginx:
        image: nginx:latest
        container_name: references_nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network


    pgadmin:
        image: dpage/pgadmin4
        container_name: references_pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: test@gmail.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"
        depends_on:
            - db
        networks:
            - app-network
    rabbitmq:
        image: rabbitmq:3.13-management
        container_name: references_rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=root
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        networks:
            - app-network

volumes:
    postgres_data:
    rabbitmq_data:

networks:
    app-network:
        driver: bridge
